# Generated by Django 4.0.4 on 2022-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_like_post_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='already_liked',
            field=models.BooleanField(default=False),
        ),
    ]
